FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv
RUN uv pip install --system --no-cache asyncua

COPY server_1000.py .

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "server_1000.py"]
